"""Initial database schema

Revision ID: 2247a813c248
Revises: 
Create Date: 2025-11-06 15:18:40.224807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2247a813c248'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=253), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('times_scanned', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_domain_name', 'domains', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domains_domain_name'), 'domains', ['domain_name'], unique=True)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_domains', sa.Integer(), nullable=True),
    sa.Column('successful_domains', sa.Integer(), nullable=True),
    sa.Column('failed_domains', sa.Integer(), nullable=True),
    sa.Column('mrt_file', sa.String(length=500), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=True)
    op.create_table('domain_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('a_records', sa.JSON(), nullable=True),
    sa.Column('aaaa_records', sa.JSON(), nullable=True),
    sa.Column('ns_records', sa.JSON(), nullable=True),
    sa.Column('mx_records', sa.JSON(), nullable=True),
    sa.Column('unique_asns', sa.JSON(), nullable=True),
    sa.Column('full_result', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_domain_scan', 'domain_scans', ['domain_id', 'scan_id'], unique=False)
    op.create_index('idx_scan_time', 'domain_scans', ['scanned_at'], unique=False)
    op.create_table('infrastructure_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('previous_scan_id', sa.Integer(), nullable=True),
    sa.Column('current_scan_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['current_scan_id'], ['domain_scans.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['previous_scan_id'], ['domain_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_change_type', 'infrastructure_changes', ['change_type'], unique=False)
    op.create_index('idx_domain_changes', 'infrastructure_changes', ['domain_id', 'detected_at'], unique=False)
    op.create_table('ip_asn_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_scan_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('ip_version', sa.Integer(), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.String(length=50), nullable=True),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('hostname', sa.String(length=253), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_scan_id'], ['domain_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asn', 'ip_asn_mappings', ['asn'], unique=False)
    op.create_index('idx_ip_address', 'ip_asn_mappings', ['ip_address'], unique=False)
    op.create_index('idx_timestamp', 'ip_asn_mappings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_timestamp', table_name='ip_asn_mappings')
    op.drop_index('idx_ip_address', table_name='ip_asn_mappings')
    op.drop_index('idx_asn', table_name='ip_asn_mappings')
    op.drop_table('ip_asn_mappings')
    op.drop_index('idx_domain_changes', table_name='infrastructure_changes')
    op.drop_index('idx_change_type', table_name='infrastructure_changes')
    op.drop_table('infrastructure_changes')
    op.drop_index('idx_scan_time', table_name='domain_scans')
    op.drop_index('idx_domain_scan', table_name='domain_scans')
    op.drop_table('domain_scans')
    op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_domains_domain_name'), table_name='domains')
    op.drop_index('idx_domain_name', table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
